In [15]:
import pandas as pd
path="C:\\Users\\kavana\\OneDrive\\Desktop\\internship\\Data\\Data\\salaries.csv"
data=pd.read_csv(path)
print(data)
print(data.info())

import sklearn
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder() #object

data['company_n']=le.fit_transform(data['company'])
data['job_n']=le.fit_transform(data['job'])
data['degree_n']=le.fit_transform(data['degree'])
print(data)


inputs=data.drop(['salary_more_then_100k','company','job','degree'],'columns')
output=data.drop(['company','job','degree','company_n','job_n','degree_n'],'columns')
print(inputs)
print(output)

import sklearn
from sklearn import tree

model=tree.DecisionTreeClassifier()

model.fit(inputs,output)

res=model.predict([[1,2,1]]) #fb,sales execurive,masters
print(res)

res=model.predict([[2,2,1]]) #google,SE,masters
print(res)

res=model.predict([[0,0,1]]) #abcpharma,BM,masters
print(res)

res=model.predict([[1,1,1]]) #fb,CP,masters
print(res)

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64
dtypes: int64(1), object(3)
memory usage: 640.0+ bytes
None
       company                  job     degree  salary_more_then_100k  \
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1
    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1
    salary_more_then_100k
0                       0
1                       0
2                       1
3                       1
4                       0
5                       1
6                       0
7                       0
8                       0
9                       1
10                      1
11                      1
12                      1
13                      1
14                      1
15                      1
[1]
[0]
[1]
[1]

C:\Users\kavana\AppData\Local\Temp\ipykernel_23992\3625045013.py:18: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  inputs=data.drop(['salary_more_then_100k','company','job','degree'],'columns')
C:\Users\kavana\AppData\Local\Temp\ipykernel_23992\3625045013.py:19: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  output=data.drop(['company','job','degree','company_n','job_n','degree_n'],'columns')
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(